
name: sololeveling
description: A Solo Leveling inspired RPG app
publish_to: 'none' # This prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  flutter_local_notifications: ^12.0.3
  http: ^0.13.5
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music.mp3
    - assets/icon.png
    Fixed pubspec.yaml to resolve dependency issues
